spring:
  application:
    name: quickstay-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5433}/${DB_NAME:quickstay}
    username: ${DB_USER:quickstay}
    password: ${DB_PASSWORD:quickstay}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:quickstay}
    password: ${RABBITMQ_PASSWORD:quickstay}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.quickstay: DEBUG
quickstay:
  payment:
    base-url: ${PAYMENT_SERVICE_URL:http://127.0.0.1:8081}
