services:
  postgres:
    image: postgres:16
    container_name: quickstay-postgres
    environment:
      POSTGRES_DB: quickstay
      POSTGRES_USER: quickstay
      POSTGRES_PASSWORD: quickstay
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  payment-postgres:
    image: postgres:16
    container_name: quickstay-payment-postgres
    environment:
      POSTGRES_DB: quickstay_payment
      POSTGRES_USER: quickstay_payment
      POSTGRES_PASSWORD: quickstay_payment
    ports:
      - "5434:5432"
    volumes:
      - payment_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: quickstay-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: quickstay
      RABBITMQ_DEFAULT_PASS: quickstay
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:
  payment_pgdata:
